@extends('layouts.notlogged')
@section('head')
    @parent
@endsection
@section('sidebar')
    @parent
@endsection
@section('bodyaccueil')
    @parent
@endsection
@section('carousel')
    @parent
@endsection
@section('footer')
    @parent
@endsection
@section('inscription')
@endsection
